onboarding = false
[ui]
prompt_new_tab_name = false
show_agent_labels_on_pane_borders = true

agent_panel_sort = "spaces"
[ui.sidebar.agents]
row_gap = 1
rows = [["state_icon", "workspace", "tab"], ["state_text", "agent"]]

[ui.sidebar.spaces]
row_gap = 1

[ui.toast]
delivery = "terminal"

[experimental]
kitty_graphics = true

[theme]
name = "catppuccin"
auto_switch = false
[theme.custom]
surface_dim = "#444477"
# idle状態をgrayに
green = "#aaaaaa"

[keys]
prefix = "ctrl+shift+/" # 無変換 -> s のcombination key

# ワークスペース
new_workspace = "prefix+n"
new_worktree = "prefix+t"
previous_workspace = "ctrl+cmd+k"
next_workspace = "ctrl+cmd+j"
rename_workspace = "cmd+shift+r"
goto = "prefix+f"

# タブ
new_tab = "ctrl+t"
previous_tab = "ctrl+shift+tab"
next_tab = "ctrl+tab"
rename_tab = "ctrl+2"
close_tab = "alt+w"             # Ghosttyでcmd+wとしてくる前提

# ペイン
split_vertical = "prefix+v"
split_horizontal = "prefix+s"
resize_mode = "prefix+e"
last_pane = "prefix+r"

# エージェント
next_agent = "shift+cmd+j"
previous_agent = "shift+cmd+k"

# サイドバー
toggle_sidebar = "cmd+i"

# その他
settings = "prefix+shift+s"

[[keys.command]]
key = "prefix+p"
type = "shell"
command = "plan"

[[keys.command]]
key = "prefix+g"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "90%"
height = "90%"


[[keys.command]]
key = "prefix+y"
type = "popup"
command = "yazi"
description = "run yazi"
width = "90%"
height = "90%"
